# Generated by Django 4.1.3 on 2023-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=20, null=True)),
            ],
        ),
    ]
