# Generated by Django 4.1.3 on 2023-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_average',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.IntegerField(choices=[(2, 'Failure 2'), (3, 'Passing 3'), (4, 'Good 4'), (5, 'Very good 5'), (6, 'Excellent 6')]),
        ),
    ]
