# Generated by Django 4.1.3 on 2023-02-09 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_city_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectclass',
            name='class_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
