# Generated by Django 4.1.3 on 2023-02-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_grade_subject_grade_subject_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
    ]
