# Generated by Django 4.1.3 on 2023-02-10 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_grade_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
