# Generated by Django 4.1.3 on 2023-02-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_parent_first_name_alter_parent_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='teacher',
        ),
        migrations.AddField(
            model_name='absence',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjectclass'),
        ),
    ]
