# Generated by Django 4.1.3 on 2023-02-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_absence_subject_remove_absence_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjectclass'),
        ),
    ]
