# Generated by Django 4.1.3 on 2023-02-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_grade_subject_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.student'),
        ),
    ]
