# Generated by Django 4.1.3 on 2023-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_subjectclass_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='accounts.student'),
        ),
    ]
